### ISSUE TITLE
Region factor levels/coding

### ISSUE THREAD

**Issue by buscandoaverroes** [worldbank/gld#12]
I noticed that the original code in PHL 2015 recodes some of the `reg` or what becomes `reg01` / `reg02` because it appears that the raw factor codes split up an existing region into "sub-regions" `a` and `b`. The issue may appear elsewhere in the project.  The original code

```
	gen byte reg01=reg
	recode reg01 (41=4)  (42=4) (17=4)
```
because using `codebook reg` you discover that there is no value for `reg=4` and `reg=41` and `reg=42` both refer to `region 4A and B` respectively. This poses two major questions/issues:

1. Can this be fully resolved via a script as planned?
2. What should actually be done with the distinct factor labels? Can we assume that the subregions should go under the missing region, and should this be done for all similar cases?

**Comment by giofsantos11** [comment]
Hi Tom! The Philippine Statistical Authority may be switching regional classification systems between [ISO](https://www.iso.org/obp/ui/#iso:code:3166:PH)) (4A  and 4B are Regions 41 and 42) and the [PSGC](https://psa.gov.ph/classification/psgc/) (4A and 4B are Regions 4 and 16) and I believe that is the source of the problem here.  It is possible that the regional classification system used is documented in the survey manual. Hence to answer your questions:

1. The above script is not going to fix it because 41 and 42 are separate regions, not one region. Not unless you are dealing with LFS before 2002 when both regions are unified. If I were to code this, I would select whichever system as standard across all the years; in this case, I select PSGC because that is a system directly developed by the PSA:
`gen byte reg01 = reg
recode reg01 (41 = 4) (42 = 17)`

This recode will apply to surveys that used the ISO system and thus, this will harmonize the factor levels across survey years.

2. No. These are not "subregions" because these are two separate regions. The only thing needed to be done is to use a single regional classification system. In the above code, I use the PSGC system so all I would do is to recode the surveys using the ISO system into PSGC. There must be some break year when the PSA switched to the PSGC system? Or is this switching every other quarter consistently?

**Comment by buscandoaverroes** [comment]
Sure, this makes sense and is super helpful. So they are actually two different regions after a point in time.

The problem is that we have LFS going back to 1997, so we are dealing with data under the old classification scheme as well. I need to look at the data again, but I'm sure you're right that there's a year where the data factor levels switch to the new classification system.

**Comment by buscandoaverroes** [comment]
update on 2003 codes: the recommended solution for the mid-year changing of region coding schema is to reconstruct the would-be regions by grouping the known provinces together. But the July round doesn't have province information (this isn't too abnormal as some years don't have province info for all 4 rounds). Putting a pause on the 2003 region year coding for now until another solution can be devised. Linking the [documentation file](https://github.com/worldbank/gld/blob/region-codes/Support/Guides%20and%20Documentation/Administrative_Levels.md).

**Comment by gronert-m** [comment]
On your comment on the fact that July does not have province info. This should not be a problem since July and October have the right region codes (41 and 42). It is only in January and April where you need the province info to convert code 4 into 41 or 42, depending on the province. 

Having said that, there seems to be another issue, namely that the regions may be wrongly coded. [Here is page 25 from the 2003 bulletin](https://psa.gov.ph/sites/default/files/ISHB_series%20no.%20116_Labor%20Force_April%202003%20.pdf):

![Capture2](https://user-images.githubusercontent.com/63501500/123616563-52750d80-d7fe-11eb-8434-1493838429e5.PNG)

You can see the provinces that make up Southern Tagalog and Central Luzon. If we look at the provinces by region code (below) you can see the info is there to do the mapping of 4 to 41 and 42. The problem is that, province **Aurora** is coded as being in region Southern Tagalog instead of Central Luzon, where it should be according to the bulletin.

![Capture1](https://user-images.githubusercontent.com/63501500/123616799-8b14e700-d7fe-11eb-8212-6aa0c17c033f.PNG)

I have played around with the sample size (the number of HHs interviewed is listed in the bulletin). The numbers do not coincide perfectly (the data has 38,382 HHs as a whole while the bulletin says there are 38,455) but you can see that the numbers are not that off. Except for Southern Tagalog and Central Luzon. Together they match what is expected (expect 9927 but data has 9894) but on their own they are off (Central Luzon has 3725 when expected is 4029; Southern Tagalog has 6,169 when expected is 5,898). This leads me to believe the Aurora case is a true error.

It seems to be the case for January 2003 as well, but July no longer (coding here is correct for region codes 41, 42, **and** 3).

I can see that you might be now asking yourself, how do I know there aren't any other errors? Should I check all regions by province? I say, that is too much. We can correct this Aurora case, but the rest is too much. Again the idea is that people, as they use the data, find errors, flag them, and we can improve them. Rome wasn't built in a day and what we should aim for is a code that is both good and improvable, not one that is _perfect_ from the get-go.

In terms of action points I suggest the following:

* Correct Aurora by sending it to region code 3 in Jan and Apr 2003
* Overwrite region codes in Jan and Apr from 4 to 41 and 42 respectively based on province
* Unite the year based on those codes
* Download all [PSA LFS Bulletins](https://psa.gov.ph/node/33231/33231/33231?combine=) and store them in the correct PHL\PHL_YYYY_LFS\PHL_YYYY_LFS_v01_M\Doc. By providing this information to users we allow them to spot issues like Aurora that in turn allow us to correct whatever may be going on in the survey.

Let me know if you have any questions

**Comment by buscandoaverroes** [comment]
Hi Mario, thanks a lot for checking this. Yes, this all makes sense. I'll correct Aurora as you suggest and overwrite the region codes for the first two rounds only, then, and follow the rest of the plan. Thanks again!

**Comment by buscandoaverroes** [comment]
reviewed in #46 and temporarily resolved, but waiting until I can run all years' code in #43 after aligning surveys to close

**Comment by buscandoaverroes** [comment]
resolved and documented in `Administrative_levels.md` in /Support
