### ISSUE TITLE
migrated_years variable in the GLD

### ISSUE THREAD

**Issue by giofsantos11** [worldbank/gld#20]
I want to seek anyone's thoughts about the variable, "migrated_years" in the GLD codebook. Should the response to number of years since last migrated be limited only to people who claimed that they have migrated during the reference period? If that is the case, then all the responses we will get for migrated_years will be equal to migrated_ref_time, which is the "reference time applied to migration questions." The following lines of code are from the do file template:

```
*<_migrated_ref_time_>
	gen migrated_ref_time = 1
	label var migrated_ref_time "Reference time applied to migration questions"
*</_migrated_ref_time_>

*<_migrated_binary_>
	destring B3_q8, gen(migrated_binary)
	recode migrated_binary (2 = 0)
	label de lblmigrated_binary 0 "No" 1 "Yes"
	label values migrated_binary lblmigrated_binary
	label var migrated_binary "Individual has migrated"
*</_migrated_binary_>


*<_migrated_years_>
	gen migrated_years = .
	destring B31_c16, gen(helper_var)
	replace migrated_years = helper_var if migrated_binary == 1
	label var migrated_years "Years since latest migration"
	drop helper_var
*</_migrated_years_>

**Comment by buscandoaverroes** [comment]
I don't think so, because the codebook also says the question can be interpreted as "how long you've lived in your current location." -- and that answer shouldn't be conditional based on if you migrated in the reference period or not, in my opinion. Then, like you say, the question really just turns into asking the reference period twice for some observations, or you have to drop them, or whatever.

**Comment by giofsantos11** [comment]
Thanks for that information from the codebook, @buscandoaverroes!

**Comment by gronert-m** [comment]
@giofsantos11 I see you closed this, but let me give you my two cents, still.

The way I structured this bit was to think of that first `migrated_ref_time` like the age application variables for the education and labour modules. This is because I had seen some questionnaires that limit migration to, for example, the last five years.

So you may have five years in `migrated_ref_time` and then `migrated_years` could be 2 since I migrated to years ago. If I have migrated 7 years ago, `migrated_years` should be 7, but since it is larger than `migrated_ref_time` the questions were never asked.

This was to help understand a reader who may see "wait, all people who migrated here are very recent, is there none that migrated 6, 7, 8 years ago?" There `migrated_ref_time` explains the questionnaire was limited to five years, w/o you having to go back to the questionnaire to understand this. This is why there are two time periods.

On the particular issue you raise, `migrated_ref_time`  should be answered for all, just like the age module restriction as it should be one and the same number for all (a general questionnaire limit), while `migrated_years` will vary (and be missing for those that have `0` for `migrated_binary`.

**Comment by giofsantos11** [comment]
Sorry that I closed too soon and thanks for still sharing, @gronert-m. 

So does this mean that your example of a person who migrated 7 years ago will not keep that information under the `migrated_years` variable? In India 2005 case, the variable `migrated_ref_time` is equal to 1 year. If I keep only those who have migrated over the past year (as indicated by `migrated_binary`), the implication is that all the responses under `migrated_years` will be equal to either 1 or missing, which does not show any interesting variation.

**Comment by gronert-m** [comment]
@giofsantos11 I will preface this by saying that I do not see the system as closed and if there is a way we can define the variables better, I am up for updating the system.

On the particular case of 2005 India I have just checked and I don't see migration questions there (which block is it?)

On the case described of a person who migrated 7 years ago, if the questionnaire were to ask did you migrate in the last year, then that person would say no. If the questionnaire then skips the rest of the migration questions, then `migration_ref_time` is 1 year as this is limiting the set of people the question is asked to. If the question is just a check box and the migration questions are asked to anyone else, then it is not functioning as a module limiter and thus `migration_ref_time` is not 1.

Further, if we assume that (for some reason) questionnaire limits the questions to only those who migrated last year, you are right that `migration_years` does not have a big range (in essence only between 0 and 1). Maybe not very informative, I agree, but that is a product of the questionnaire design, which is beyond what we can do.

**Comment by giofsantos11** [comment]
My apologies, I was referring to 2007 survey not the 2005 one. My bad! 

I should have added other important details here: the survey has two migration variables: `B3_q8` (whether the HH migrated to the village during the last 365 days), and `B31_c6` (period, in years, since leaving the HH). The latter variable is from a module, `Block-3dot1-out-migrants-records`, which contains "particulars of the out-migrants, who migrated out any time in the past". The `B31_6` variable asks everyone who has migrated even beyond the one year reference period.

**Comment by gronert-m** [comment]
Indeed `B3_q8` asks whether the household migrated (as a whole) in the past 12 months. But the questions of block 3.1 are about members who **migrated out of the household** (question `B3_12`)

![image](https://user-images.githubusercontent.com/63501500/122057079-257a3100-cde2-11eb-9cdd-b374a112fc0f.png)

That question is not time limited and thus you have those answers that can go back in time.

```
whether   any   former   member   of   the household  migrated  out  any  time  in  the past (yes  -1, no –2)
```

**Comment by giofsantos11** [comment]
Got it. The GLD variable, `migrated_binary`, as defined in the guidelines, is at the individual level. That means, I am not supposed to use the 2005 India EUE variable, `B3_q8` since it is asked for the household. 

My next question now is, should I use information from the B31 module (module on out-migrants) to code the GLD variable, `migrated_binary` (defined as "whether the individual has ever migrated)? And if so, the value for `migrated_ref_time` should be equal to 99, correct?

**Comment by gronert-m** [comment]
I had not thought about it, but I guess I share your view that migration is defined at the individual level in the guidelines and this is only household so I would not use that information.

Neither would I use the migration out of a household because that is not migration (necessarily) as we think about a household moving but rather certain members (that are not interviewed) left it. That is a different view and one that is (in my view) not common in questionnaires and not one we are interested in. So I would, in the case of 2007, leave all of migration blank.

**Comment by giofsantos11** [comment]
Thanks @gronert-m!

**Comment by gronert-m** [comment]
@giofsantos11 If you are happy with the outcome of the discussion, please close the issue.
