### ISSUE TITLE
I2D2/GLD Harmonization Across all surveys?

### ISSUE THREAD

**Issue by buscandoaverroes** [worldbank/gld#62]
A two-part question/idea, 

@alexandraqn @giofsantos11 @gronert-m @Junying-T 

1. Should we remove the value labels that were defined in the incoming/raw data and only leave the value labels that we use? For example, an "urban" variable could be labeled as `"0 Rural    1 Urban"`, but we change it to the label specified in the I2D2 or GLD dictionary:
```
label define      urban     "1 Urban 2 Rural"
```
Shouldn't the original urban value label be removed explicitly? The resulting .dta file will now have two urban value labels: one is used in the dataset and one is irrelevant. This could be confusing to the user.

This made me think of another idea:

2. Since all of our final value labels for I2D2 or GLD should be the same, why could we not have one central place to pull these value labels from and avoid a) retyping them every time, and b) potentially committing errors as we type them? This way we know that every I2D2 or GLD value labels are the same across all datasets. This could be implemented in the form of a central .do or .ado file that literally just defines all the value labels by hand or reads it from the codebook xlsx files -- kept next to our code folders and called in our code (or even just copy-paste). (I guess you could have the script apply the labels as well, since you always know that the "urban" label will be applied to the `urb` I2D2 variable, you would just run it at the end of your code after all variables are made)

Thoughts?

**Comment by alexandraqn** [comment]
Hi Tom, 
On your first point, I think I understand what you mean. However, I opened my final datasets harmonized (GLD and I2D2) and in both case the value labels were unique. It is true that some of them reference original (raw) data information, especially in the I2D2 but I don't know if we need to  explicitly delete it before moving to the last part of the code that consolidates the variables and keeps only those created and drops others. Please, feel free to correct me if I missed a point here.

Now,  on your second point, I agree, I also found it cumbersome and prone to error to manually code labels. Perhaps there could be a similar template to the check where you call labels from multiple do files (GLD). The only problem I see with this is that we can do this retrospectively and not forward looking because of the possible changes in methodology for labels in some countries (talking about regions for instance). 

I would love to hear what others think, thank you for opening this discussion. 
-Alexandra

**Comment by gronert-m** [comment]
Hi @buscandoaverroes ,

I think Alex's idea of working on the template is the right way forward. First, even if the labels are the same across the datasets (they are GLD and not CCC_YYYY_Survey labels) the overriding logic here is, as said at the beginning, no person is an island - but surveys are! That is, a person, if given the harmonization code should be able to find the whole (or as much as possible of the) process of moving from raw to harmonized. This is in case they want to amend the harmonization to their liking, they do not need a second file with labels to read in.

In terms of the template, we can expand it to drop labels not used after reducing to the variables we want to keep, to clean up unused labels. This can be done in Stata, although it is a bit clunky. At least I have had a look and not yet found it. Below is my proposal.


```

sysuse auto, clear

* Create an unused label
label define fruit 1 "Apple" 2 "Pear"

* Store all labels in data
label dir
local all_lab `r(names)'

* Store all variables with a label
ds, has(vallabel)
local used_lab `r(varlist)'

* Local to drop
* This is the bit I do not know, I think in Stata I will have to go through loops. In an Stata-R hybrid pseudo code my idea is
local to_drop = all_lab !%in% used_lab
for each (lab in to_drop){
   drop `lab'
}
```

This could be appended to the template. But I don't know how to do the last part. Anyone wants to take this challenge up?
